"""Initial migration

Revision ID: 0001
Revises: 
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=True)
    
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('expected_start_time', sa.String(length=10), nullable=True),
    sa.Column('employee_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_index(op.f('ix_employees_username'), 'employees', ['username'], unique=True)
    
    op.create_table('current_time_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('time_in', sa.String(length=10), nullable=True),
    sa.Column('time_out', sa.String(length=10), nullable=True),
    sa.Column('break_in', sa.String(length=10), nullable=True),
    sa.Column('break_out', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Enum('ON_DUTY', 'ON_BREAK', 'OVERTIME', 'LATE', 'UNDERTIME', 'ON_TIME', 'NO_RECORD', 'NOT_STARTED', 'COMPLETED', name='employeestatusenum'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_index(op.f('ix_current_time_tracking_id'), 'current_time_tracking', ['id'], unique=False)
    
    op.create_table('time_records',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('expected_time_in', sa.String(length=10), nullable=True),
    sa.Column('expected_time_out', sa.String(length=10), nullable=True),
    sa.Column('time_in', sa.String(length=10), nullable=True),
    sa.Column('time_out', sa.String(length=10), nullable=True),
    sa.Column('break_in', sa.String(length=10), nullable=True),
    sa.Column('break_out', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Enum('ON_DUTY', 'ON_BREAK', 'OVERTIME', 'LATE', 'UNDERTIME', 'ON_TIME', 'NO_RECORD', 'NOT_STARTED', 'COMPLETED', name='employeestatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_records_id'), 'time_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_time_records_id'), table_name='time_records')
    op.drop_table('time_records')
    op.drop_index(op.f('ix_current_time_tracking_id'), table_name='current_time_tracking')
    op.drop_table('current_time_tracking')
    op.drop_index(op.f('ix_employees_username'), table_name='employees')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
